name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.3' # Ou votre version cible
          check-latest: true
          cache: true # Active automatiquement le cache des modules et du build

      - name: Install dependencies
        run: go mod download

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt ./...

      - name: Security Scan (Govulncheck)
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...
